### ISSUE TITLE
maybe force RUNNING HANDLER [bdellegrazie.ca-certificates : update ca-certificates ...]

### ISSUE THREAD

**Issue by iiegn** [bdellegrazie/ansible-role-ca-certificates#3]
My problem is that after certs have been installed in a playbook the tasks in a subsequent role fail because the `update ca-certificate` handler has not run. The handler will be triggered at the end of all roles - but this point is never reached.

I am not sure whether this is problem of this role - or a more general problem of how handlers interact with roles, playbooks, tasks, etc. 

However, my interim solution is to add a ```meta: flush_handlers``` - and i can send a PR for this...

**Comment by bdellegrazie** [comment]
I'm not against the idea however `meta: flush_handlers` flushes *all* handlers which may have unintended side-effects in some circumstances.

What about a register variable and then explicitly triggering the command at the end of the role?

**Comment by iiegn** [comment]
i see, yes, it does flush _all_ handlers. 

so, keeping `notify` "this variable triggers update of OS of CA certificates" and make it something like "this variable represents the command to trigger an update of OS CA certificates when handlers are run". additionally, a new variable like, for example `immedate_update` "yes/no: this variable triggers an immediate  update of the notify trigger at the end of the role instead of when handlers are usually run"?

as it is, i expected `notify` to already do the job (and had to learn that handlers are run later... even after a role has already ended).
